apply.sh
destroy.sh
readme.md

Realpath isn't installed on OSX and new versions of debian by default. 
The error message we throw isn't very helpful when it isn't installed too.
By expecting an absolute path instead, we let users use their own tools when calling make apply.

Use absolute path, as realpath is an additonal dependency

---

addons/cloudfront_distribution.tf

Creates a cloudfront distribution
Features: 
- Can auto-generate cert or use an existing one (to support additional aliases)
- Can create a log bucket or use an existing one
- Can be tuned for different use-cases (sane defaults for OWS)
Dependencies:
- need to create an alb-ingress controller with "cached-alb.domainname"(customisable) to use cloudfront distro

Cloudfront distribution addon

---

apply.sh
destroy.sh
drain_and_wait.sh
nodes/main.tf
nodes/modules/workers/outputs.tf
nodes/modules/workers/variables.tf
nodes/modules/workers/worker_image.tf
nodes/modules/workers/workers.tf
nodes/outputs.tf
nodes/variables.tf
patch.sh

Allows cluster admins to run a patch script to perform a blue / green node deployment with a new AMI. Introduces a new workspace `$WORKSPACE-green` which will be default not be enabled.
Blue / Green patching remains optional. Using `apply.sh` to update the AMI of the blue worker group is still available.

Blue / Green patching scripts

---

apply.sh
infra/outputs.tf
nodes/main.tf
nodes/modules/workers/variables.tf
nodes/modules/workers/worker_image.tf
nodes/variables.tf

Add a variable for additional EC2 userdata commands passed to the EKS worker nodes.
Update the outputs for infra to include the cluster role arn.
Update the apply script to use the role-arn from the infra module when setting the EKS kubeconfig

Allow additional EC2 userdata for EKS worker nodes

---

infra/modules/eks/user_policy.tf
infra/outputs.tf

The condition that MFA is a requirement for valid credentials is invalid for SSO users and causes credential failures.

Remove MFA conditions from user_policy so SSO credentials can be used

---

docs/getting_started.md
docs/patching.md
docs/patching_upgrading.md
examples/quickstart/workspaces/datakube-dev/terraform.tfvars
infra/main.tf
infra/modules/eks/_variables.tf
infra/modules/eks/master.tf
infra/variables.tf

This PR will allow (and also require) the EKS cluster version to be specified in terraform. When running this the `cluster_version` variable must be specified in your `terraform.tfvars` files. This PR will allow the cluster version to be updated using Terraform.

Require specification of EKS cluster version

---

examples/quickstart/backend/terraform-backend.tf

Terraform wants to have `tags = {` instead of `tags {`, otherwise it complains. Fixed accordingly.
```
$ make create-backend region=ap-southeast-2 backend=datakube-dev
Initializing the backend...
Initializing provider plugins...
The following providers do not have any version constraints in configuration,
so the latest version was installed.
To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.
* provider.aws: version = "~> 2.16"
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. …
```

Use equal signs for tag blocks

---

addons/_variables.tf
addons/cluster_autoscaler.tf

Sets scale-down-uneeded-time which defaults to 10 minutes but can be adjusted using the new variable

Add a variable to allow configuration of the autoscaler scale down time

---

addons/cluster_autoscaler.tf

This simple change enables cluster-autoscaler to support the mixed instances policy in ASG for SPOT instances - vastly improving the ability to schedule SPOT instances.
- Instructions on how to configure your ASG can be found [here](https://github.com/kubernetes/autoscaler/tree/cluster-autoscaler-release-1.14/cluster-autoscaler/cloudprovider/aws). It translates to terraform simply enough.
- If you look at that link closely you will find you are on a branch. That is the 1.14 release branch and only 1.14 or higher support this feature.
- Whilst the cluster-autoscaler notes say the version number should match the k8s version number (1.14 with this update), in the fine print it says that is what they _test_ and higher version numbers often work with previous k8s versions. AWS is clearly …

Updatge cluster-autoscaler version to provide support for mixed instance types in SPOT

---

addons/fluxcloud.tf

In order to create a spec.template.metadata.labels , the config should match the spec.selector.match_labels.
I have created a `spec.selector.match_labels` to match the template label as provided in doc on terraform 
https://www.terraform.io/docs/providers/kubernetes/r/deployment.html?origin_team=T0L4V0TFT#labels
```By default, the provider ignores any labels whose key names end with kubernetes.io. This is necessary because such labels can be mutated by server-side components and consequently cause a perpetual diff in the Terraform plan output. If you explicitly specify any such labels in the configuration template then Terraform will consider these as normal resource attributes and manage them as expected (while still avoiding the perpetual diff problem). Must match selector```

 update terraform file for fluxcloud parameters set up

---

nodes/main.tf
nodes/modules/workers/worker_image.tf
nodes/modules/workers/workers.tf

Same error message as in https://github.com/terraform-aws-modules/terraform-aws-acm/issues/10. This
change enables the cluster to be destroyed in one go.

Fix invalid count arguments

---

nodes/modules/workers/worker_image.tf

This will enable the use of node affinity to only run certain workloads on spot instances or on normal instances.

Spot labels

---

addons/fluxcloud.tf

Flux is currently being deployed in the `flux` namespace, this change ensures that fluxcloud is also deployed in this namespace so they can communicate.
This change places a dependency from the fluxcloud addon to flux addon, but as fluxcloud requires flux to be useful, I don't believe this is a problem.

change fluxcloud to be in the flux namespace

---

nodes/modules/workers/worker_image.tf

Adding additional meta-data about each node makes it easier to perform system operations like patching nodes
Instances will advertise their current AMI-ID to any users with permissions to read them, potentially a concern if you have over-privledged users and un-patched nodes.

add instance-id and ami-id to node labels

---

nodes/modules/workers/worker_image.tf

Add the same insatance and ami id labels to spot nodes

Instance labels for spot nodes

---

infra/main.tf
infra/variables.tf

We need more storage than 180 GiB
None, all defaults are the same.

allow changing db storage size

---

addons/prometheus.tf

deleting prometheus leaves an extra crd that isn't being cleaned up properly, causing re-installs to fail.
none

add missing crd to prometheus cleanup scripts

---

infra/modules/eks/lb_sg.tf
infra/modules/eks/worker_sg.tf

Creates a generic security group that can be used in alb-ingress-controller (or any other ingress controller) to reduce the proliferation of Security groups as per https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/682
Due to the reliance on the node security group this change can't be made in the addons folder, as it can potentially be used in other ingress-controllers I've chosen not to create it only when alb ingress controller is enabled.

add shared security group for alb's to use

---

addons/jhub_cognito_auth.tf

> To date addons have been configurable as optional. A recent update to jhub-cognito-auth and the new waf module seem to break this pattern. This PR makes all resource in jhub-cognito-auth respect the enabled flag.

Make all jhub_cognito_auth resources optional

---

docs/variables.md
infra/main.tf
infra/modules/database_layer/_variables.tf
infra/modules/database_layer/db.tf
infra/variables.tf

This change will enable rds storage autoscaling, which will reduce the chances of outages to apps on these clusters, by scaling rds storage instead of failing.
None, this change is entirely optional, leaving the max_db_storage to 0 will have no changes
I also fixed a small bug in doco for db_storage var.

Add optional setting to enable rds storage autoscaling

---

infra/main.tf
infra/modules/setup/coredns_config.tf
infra/modules/setup/variables.tf
infra/outputs.tf

…ing local-exec provisioner
Currently the coredns config is generated, but not automatically applied as a pod restart is required. 
We have automated a rolling deployment of the coredns pods after the config is updated by creating coredns custom config and apply rolling update using local-exec provisioner on resource config change. This will enable the database.local domain to be automatically configured on new deployments.
The changes will roll update kubernetes cordns custom config on config change automatically. No manual step require to create and apply to coredns pod. There is a few seconds of outage first …

add coredns config map resource and patch update coredns config automatically on config update 

---

docs/variables.md
nodes/main.tf
nodes/modules/workers/worker_image.tf
nodes/modules/workers/workers.tf
nodes/variables.tf

Currently we create a single ASG per AZ and per nodetype, when using both spot and ondemand node types this means you will have 6 ASGs, this choice was made as ASG AZ rebalancing can mess with cluster autoscaler. 
This approach works, but raises additional issues:
- min number of nodes is min number of ASGs
- autoscaling from 0 can be a bit broken, cluster autoscaler will sometimes scale up one asg and leave other ones
To simplify deployments for new instances we now support new x_nodes variables:
- min_nodes
- max_nodes
- desired_nodes
- min_spot_nodes
- max_spot_nodes
The _nodes_per_az variables should still work if _nodes variable is >0 we use that, otherwise we will combine _nodes_per_az by the number of deployed AZs
This change has been tested without adding the new *_nodes …

Multi AZ ASG

---

nodes/modules/workers/workers.tf

This is an enhancement of #130 to support autoscaling from 0 for each node group type by adding require tags to ASG. This change will allow us to define ASG  min size and desire capacity set to zero and cluster-autoscaler can take care of scaling from 0.
No breaking changes. Added below tags to ASG:
- k8s.io/cluster-autoscaler/${var.cluster_name}
- k8s.io/cluster-autoscaler/node-template/label/nodetype

Enable Auto-scaling from 0 #133

---

addons/waf.tf

Set default value for waf_environment. This should be optional parameter if you don't want to configure WAF. Make this addon optional. 
Fix the WAF configuration. No impact.

set default value - waf_environment

---

scripts/roll_instances.sh

roll_instances script - comment set -e - will revisit a script later. Adding set -e doesn't ignore the error.
No impact

commented set -e - will revisit a script later

---

addons/cloudfront_distribution.tf

The cloudfront distribution addon fails to set local variable `certificate_arn` if `cf_certificate_arn = ""` and `cf_certificate_create=false`. This has broken sandbox pipeline.
To mitigate the issue, the `certificate_arn` is set with similar logic in terraform-
if var.certificate_arn != "" then
certificate_arn = var.certificate_arn
else if var.cf_certificate_create then
certificate_arn = aws_acm_certificate_validation.cert[0].certificate_arn
else
certificate_arn = ""

update condition logic for certificate_arn local variable

---

docs/variables.md
infra/main.tf
infra/modules/eks/_variables.tf
infra/modules/eks/user_policy.tf
infra/variables.tf

This change is to support EKS user role to have additional policies to allow access to different AWS services using EKS assume role. This change will allow user to test thing locally.
No impact. Enhancement. User role to have additional policies.

optionally update user policy

---

addons/cloudfront_distribution.tf
docs/variables.md

Cloudfront distribution logging configuration is currently in broken state and not delivering any logs. This PR is to fix below two issues -
- bucket configuration - missing bucket policy
- cf logging configuration 
No Imapact. Enable logging functionality - cloudfront distribution. 
How to use:
cf_log_bucket_create = true   # Flag to create a bucket
cf_log_bucket = <bucketname> # Bucket name use for forwarding cf logs to
If cf_log_bucket_create = false, then must configure bucket as per cf guidelines.

Fix cf log bucket

---

addons/kubewatch.tf
docs/kubewatch.md
docs/variables.md

- Existing k8s infra is using Flux cloud to alert slack when there is/are change/s in the datakube-apps repo. However, slack alert to notify when the change actually is being deployed in the eks cluster is missing. This PR adds bitnami's `kubewatch`, a Kubernetes watcher that currently publishes notification to Slack upon actual changes to k8s resources.
- The changes implemented as part of this PR is an add-on that by default is disabled and hence would not affect any existing infra setup.

Add kubewatch to monitor k8s resources

---

addons/kubewatch.tf

- `kubernetes_namespace` `monitoring` is defined in `prometheus.tf` file
- None

Remove duplicate kubernetes namespace, monitoring

---

docs/variables.md
infra/main.tf
infra/variables.tf

Addresses injection of DB version via TF variables
Needs to be tested in dev cluster builds before being upgraded in prod since the upgrade path from 9.6 -> 11.5 is not straight-forward. Also needed will be postgis version matches and in-tandem upgrades. This has been captured in #144.

#143 Allow injection of postgres version

---

addons/service_account_roles.tf
docs/variables.md

Provision OpenID Connect (OIDC) identity provider, IAM roles for service-account and trusted policy to support fine-grained IAM role based access to pod level using service accounts. This change is made to test the functionality and address #122 
No it is an optional addons.

Service role

---

addons/config/efs-provisioner.tpl
addons/efs.tf
docs/variables.md
scripts/roll_instances.sh

This change creates an addon for EFS storage, this is required for running zero-to-jupyterhub in a multi-az deployment as cluster autoscaler will struggle to connect the AZ with the disks users are using. Instead we create a single shared EFS volume and give each user their own folder in this disk, which is mounted to their jupyterhub container.
This PR should close #120 
I've tested enabling / disabling
and running alongside existing Z2JH user pods with gp2 pvcs
If you have existing user pvcs (gp2) you'll have to delete them for a new efs pvc to be created for that user.

add EFS addon and documentation

---

addons/waf.tf

- WAF configuration - expose max_expected_body_size to support large payload. This changes is needed for jupyter hub.
- No impact.

exposed var max_expected_body_size - WAF configuration

---

examples/stage/odc_k8s/odc_k8s.tf
odc_k8s/config/flux.yaml
odc_k8s/flux.tf
odc_k8s/install_extra_software.tf

Update to flux/helm-operator current stable release (flux 1.17.0)
If there is an existing fluxcd deployment this will replace it and possibly not upgrade in place. It may well change the ssh public key in use to auth to the git repo so that will need updating in the repo as well. Unfortunately I've been unable to find any "upgrading" instructions and I don't have an old version to test against.
I suggest first turn off the flux deployment in terraform to remove it and then turn it on with the update in place might be a good start.

Flux cd install refactor

---

odc_eks/outputs.tf

Additional outputs for use by other terraform components.
In this particular case its useful in the [flux-odc-sample/odc_k8s_core.tf](https://github.com/opendatacube/flux-odc-sample/blob/test-flux-release/tf/examples/stage/odc_k8s_core.tf) so the region,owner,namespace,and environment vars can be set from the remote state for the eks/k8s cluster.

Test flux release robw

---

docs/variables.md
nodes/main.tf
nodes/modules/workers/variables.tf
nodes/modules/workers/worker_image.tf
nodes/modules/workers/workers.tf
nodes/variables.tf

- Updated nodes ASG per AZ instead multiAZ auto-scaling group to support EBS volume for jupyterhub. Also made nodes variable to configure per availability zone.
e.g.
min_spot_nodes = {
ap-southeast-2a = 0
ap-southeast-2b = 0
ap-southeast-2c = 0
}
- No impact as changes made also supports backward compatible

asg update - ASG per availability zone

---

cognito/cognito_auth.tf
cognito/output.tf
cognito/variables.tf
examples/stage/odc_k8s_sandbox/config/jhub.yaml
examples/stage/odc_k8s_sandbox/jhub.tf
examples/stage/odc_k8s_sandbox/odc_k8s_data_providers.tf

This modification allows for the email message being sent when admins create account to be customised.
NOTE: AWS Cognito has changed it parameters for the validity of unused temporary passwords and at the moment the tf AWS provider doesn't support this parameter. As a result it is necessary to use a workaround that prevents TF from doing anything with that value. The module has been configured with that workaround. See the code changes for a link to the details.
The module includes a default configuration in the event one isn't provided. It's very nearly the same behaviour so there shouldn't be any side effects …

Additional config for cognito

---

odc_user/output.tf
odc_user/user.tf
odc_user/variables.tf

- created odc_user module - this will use to provision user and sets its policy.
usage:
```
module "odc_user_jupyterhub" {
source = "github.com/opendatacube/datacube-k8s-eks//odc_user?ref=new-odc-user-module"
owner = local.owner
namespace = local.namespace
environment = local.environment
tags = {
"stack_name" = local.cluster_id
"department" = "geoscience australia"
}
user = {
name = "test-user"
policy = <<-EOF
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"S3:ListBucket"
],
"Resource": [
"arn:aws:s3:::dea-public-data"
]
}
EOF
}
}
```

added new module odc_user to support creating IAM user

---

addons/main.tf

Newer version of helm provider not supporting tiller so need to pin the version -> 0.10.4
Fix helm provider - pipeline broken

pin helm provider version to 0.10.4 - newer version is not supporting tiller

---

odc_eks/cloudfront_distribution.tf
odc_eks/main.tf
odc_eks/modules/database_layer/db.tf
odc_eks/modules/database_layer/rds-sg.tf
odc_eks/modules/eks/lb_sg.tf
odc_eks/modules/eks/master_sg.tf
odc_eks/modules/eks/worker_policy.tf
odc_eks/modules/eks/worker_sg.tf
odc_eks/modules/eks/workers.tf
odc_eks/waf.tf
odc_k8s/cloudwatch_logs.tf
odc_role/role.tf
odc_user/user.tf

Name tag gets ignored by AWS because name tag has to be "Name" and not "name" so this fix
Name tag gets ignored by AWS due to tag mismatch

Fix Name tag

---

cognito/cognito_auth.tf
cognito/variables.tf

Enable cognito prevent destroy option
No imapact. Default is set to false and it will destroy cognito same as current setup.

add a variable to prevent destroy cognito

---

cognito/README.md
cognito/cognito_auth.tf
cognito/variables.tf

- Cognit module enhancement - update cognito app client settings so we can experiment with jupyterhub enhancement/upgrade work. Looking into upgrading latest chart release, cognito authenticator class (https://github.com/jupyterhub/oauthenticator/pull/269/files) and few other enhancements 
- No impact. Changes are made such that it works with older version of the cognito module. But recommending  to make necessary changes as we progressing with odc-1.8.
** Recommendation **
- use `callback_urls` instead of `callback_url` which accepts lists of urls.
- `default_redirect_uri` and `logout_urls` are optional …

update cognito app client settings for callback_urls, default_redirect_uri and logout_urls

---

examples/stage/01_odc_eks/odc_eks.tf
odc_eks/README.md
odc_eks/cloudfront_distribution.tf
odc_eks/waf.tf

- Make WAF bucket create optional
- No impact. Default is set to false so set `waf_log_bucket_create` to true.

make waf log bucket creation optional

---

odc_eks/README.md
odc_eks/waf.tf

current`01_odc_eks/waf.tf` uses module created by [`traveloka/terraform-aws-waf-owasp-top-10-rules`](https://github.com/traveloka/terraform-aws-waf-owasp-top-10-rules) has two issues - 
- module is written using terraform version < 0.12 and throws warning 
- Cross-site scripting is currently stoping user to save notebook files and we cannot disable the XSS filters because it doesn't support optional rule creation - check [FAQ](https://github.com/traveloka/terraform-aws-waf-owasp-top-10-rules#faq). 
To fix this problem, created a ODC fork from [PR](https://github.com/traveloka/terraform-aws-waf-owasp-top-10-rules/pull/17) created by `Matt Gowie`. This  PR exactly does what we after and …

updated WAF module source to point to ODC fork

---

examples/stage/01_odc_eks/odc_eks.tf
odc_eks/README.md
odc_eks/waf.tf

- Test waf module - extended waf module to meet our need - [`opendatacube/terraform-aws-waf-owasp-top-10-rules`](https://github.com/opendatacube/terraform-aws-waf-owasp-top-10-rules)
- This module extends to solve -
* Updates to address all Terraform 0.12 warnings
* Updates to split owasp-top-10-rules into each tf files
* Updates to allow disable specific XSS and  rules
* Updates to address URL whitelisting
- Review this PRs:
WAF module enhancement - https://github.com/opendatacube/terraform-aws-waf-owasp-top-10-rules/pull/1
followed by url whitelisting - https://github.com/opendatacube/terraform-aws-waf-owasp-top-10-rules/pull/2
> Will making this change break or change an existing …

Waf module enhancement

---

cognito/README.md
cognito/cognito_auth.tf
cognito/output.tf
cognito/variables.tf

- We wanted use same cognito user pool for multiple applications, e.g. jupyterhub, airflow. This allows us to manage users who can have access to multiple applications using same user account.
- No impact. Introduce new variable `app_clients` to configure user pool app clients. check the README `usage`.

added support to create additional user pool clients to manage multiple apps

---

odc_eks/modules/eks/worker_image.tf

- There is a param `max_spot_price` but never been used to set spot max price. This PR will solve this issue #214.
- update spot node launch template. require to execute roll instance script to apply this change.

enable spot price settings for spot nodes

---

odc_k8s/README.md
odc_k8s/aws_auth.tf
odc_k8s/variables.tf

aws_auth enhancement - accepts user_config_template and role_config_template optional parameters. This will allow us to override  aws-auth `mapRoles` and `mapUsers` settings (rather than default config - set as part of `aws_auth.tf` tf template). 
Benefit - 
- more flexibility in setting `aws-auth` 
- manage user access with different permission to cluster become easy and manage in your live repo like -
```
data "template_file" "map_user_config" {
template = <<EOF
%{ for user_name, user_arn in local.admin_users ~}
- userarn: ${user_arn}
username: ${user_name}
groups:
- system:masters
%{ endfor ~}
%{ for user_name, user_arn in local.web_users ~}
- userarn: ${user_arn}
username: ${user_name} …
```

aws_auth enhancement - accepts user_config_template and role_config_template param

---

examples/backend_init/terraform-backend.tf
odc_eks/modules/eks/workers.tf

Updated backend_init example module - added `aws_s3_bucket_public_access_block` resource to config s3 public access block to solve #227 
No impact

Backend init s3 policy

---

cognito/README.md
cognito/cognito_auth.tf
cognito/output.tf
cognito/variables.tf
examples/stage/01_odc_eks/cognito.tf
examples/stage/01_odc_eks/outputs.tf
odc_eks/modules/eks/workers.tf

- `cognito` module currently uses count to loop through `app_clients` and `user_groups` variable to provision resources. By doing this we need to remember the order of the resource - This is fragile. This PR enhance `cognito` module to solve issue #226 and #210 
- Yes. If you are migrating from odc terraform version `v1.8.0`, then you are require to change cognito.tf configuration as per README.  e.g. -
```
module "cognito_auth" {
source = …
```

Issue 226 cognito

---

cognito/README.md
cognito/provider.tf
cognito/variables.tf

- This will solve issue - #232.
- default value for `region` is set to `ap-southeast-2`. so all the resources created by this module in this region only. Please provide value for `region` attribute if that is not the case.

cognito module - support for region

---

cognito/README.md
cognito/provider.tf
cognito/variables.tf

- Remove region and provider from cognito module instead will manage provider from root module as suggested in issue #235. 
- Thanks @woodcockr

remove provider from cognito module as rob suggested

---

odc_eks/modules/eks/worker_policy.tf

- AWS SSM managed role `AmazonEC2RoleforSSM` will will soon be deprecated. so changed it to use new role instead.
- solve #237. No impact.

updated AWS SSM manage role

---

odc_eks/modules/eks/worker_policy.tf
odc_k8s/README.md
odc_k8s/config/flux.yaml
odc_k8s/flux.tf

- flux chokes on unavailable image from registry (mainly external images where we don't have control) and flooding logs so added optional variable `flux_registry_exclude_images` to instruct Flux to exclude these images from auto-release
> ts=2020-07-08T06:30:58.891563087Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/cilium/cilium auth={map[]} warn="manifest for tag svc-v2-fix-1.5.0 missing in repository docker.io/cilium/cilium" impact="flux will fail to auto-release workloads with matching images, …

Allow flux to support registry exclude image option

---

odc_k8s/README.md
odc_k8s/config/flux.yaml
odc_k8s/flux.tf

- Update flux configuration yaml file - optional configuration for rbac + service account role + ecr. This will allow flux to monitor ECR private repositories
- No impact.

Fluxcd ecr support

---

odc_eks/modules/eks/worker_image.tf
odc_k8s/flux_helm_operator.tf

- Added Amazon EKS account support for Cape town region - "877085696533"
- Upgraded fluxcd helm-operator version to `1.2.0` 
- It will rollout new pods for fluxcd helm-operator

Cape town region support for EKS

---

odc_k8s/flux_helm_operator.tf

- Re apply helm operator crd on helm version update. Fluxcd helm-operator version upgrade also require update to helm CRD otherwise it breaks the deployment and constantly try to apply hr upgrade in a loop. This PR will fix this.
- Required it for helm upgrade from 1.0.2 -> 1.2.0.
- apply CRD on helm version upgrade.

reapply helm operator crd on helm version update

---

odc_eks/cloudfront_distribution.tf

the odc_eks/cloud_front_distribution.tf currently declares a aws provider for region us-east-1 as this is required for cloudfront. Unfortunately the explicitly declared module provider means you can't specify AWS credentials for the provider to use from the caller. 
The correct approach is to use a Module Provider Alias in the module and then have the caller provide the AWS Provider like this:
```
provider "aws" {
region = "us-east-1"
alias  = "use1"
max_retries = 10
access_key = data.vault_aws_access_credentials.creds.access_key
secret_key = data.vault_aws_access_credentials.creds.secret_key
}
module "odc_eks" {
source = "github.com/opendatacube/datacube-k8s-eks//odc_eks?ref=make-cf-aws-provider-a-proxy"
providers = {
aws.us-east-1 = aws.use1
}
region          = local.region
owner …
```

Make cf aws provider a proxy

---

odc_eks/main.tf
odc_eks/modules/eks/variables.tf
odc_eks/modules/eks/workers.tf
odc_eks/variables.tf

Adds an option to add additional tags to worker nodes.
In our case required for corporate IT required tagging but handy to have in general
Nil - if you don't use them it will default to previous behavior

Add extra tags option specifically for nodes

---

cognito/cognito_auth.tf

Closes #251 , by adding tested PinPoint analytics for Cognito.
This change makes cognito + pinpoint analytics functional in regions that are not us-east-1
Adds new functionality, no negative effects. There are couple of dangling pinpoint roles which will be cleaned up in a separate PR. See follow on issue #263.

#251 Use application ARN instead of ID

---

.github/pull_request_template.md
cognito/cognito_auth.tf
odc_eks/README.md
odc_eks/main.tf
odc_eks/variables.tf

expose a new optional variable - `enable_s3_endpoint` and set it's default value to `true`. Needed it exposed for our africa clusters
No impact as it is an optional variable with default set to "true"

expose a new optional variable - enable_s3_endpoint

---

examples/backend_init/terraform-backend.tf
examples/stage/01_odc_eks/odc_eks.tf
odc_eks/cloudfront_distribution.tf
odc_eks/main.tf
odc_eks/versions.tf
odc_eks/waf.tf

+ deployment label module updated.
+ syntax fixes for WAF (via module version update and related PR)
+ provider alias syntax change for cloudfront aws us-east-1 provider.
**Any PRs will require running `terraform fmt -recursive` successfully first. Please install terraform version `v0.15.x` on your local setup for this activity.**
TF 0.15.x fully deprecates some older features - notably list() - and uses a different syntax for provider aliases (no more empty provider blocks).
THERE SHOULD BE NO CHANGED TO INFRASTRUCTURE FROM THESE CHANGES

Upgrades for tf 0.15.x syntax changes

---

cognito/README.md
cognito/cognito_auth.tf
cognito/variables.tf
odc_eks/versions.tf
odc_k8s/fluxcloud.tf
odc_k8s/variables.tf
odc_role/variables.tf
odc_user/variables.tf

**Any PRs will require running `terraform fmt -recursive` successfully first. Please install terraform version `v0.13.5` on your local setup for this activity.**
cognito - support token validity configuration. This is per app-client configuration and it's default is set to below:
```
token_validity_units = {
access_token  = "minutes"
id_token      = "minutes"
refresh_token = "days"
}
access_token_validity  = 60
id_token_validity      = 60
refresh_token_validity = 30
```
It can impact so make sure either go with defaults or override to your configuration.

cognito - support token validity configuration

---

contributing.md

**Any PRs will require running `terraform fmt -recursive` successfully first. Please install terraform version `v0.13.5` on your local setup for this activity.**
Closes #19 
Will require repository specific refinements.

#19 Add ODC boilerplate contrib guide

---

CHANGELOG.md
odc_eks/README.md
odc_eks/main.tf
odc_eks/outputs.tf
odc_eks/variables.tf

Some deployments have IT requirements that necessitate the use of an alternate VPC configuration to the default created by the `odc_eks` module. This PR makes VPC creation optional and allows for the VPC and subnets to be supplied to the `odc_eks` module.
Making `odc_eks.module.vpc` optional adds a `count` and the resource path for the default `create_vpc = true` configuraiton changes to `odc_eks.module.vpc[0]`. It is thus necessary to `terrafrom state mv` all of these resources to the new path. The new `CHANGELOG.md` contains the necessary commands.
Once the resource names are updated there is _no change to …

Vpc creation optional

---

odc_k8s/README.md
odc_k8s/config/flux.yaml
odc_k8s/flux.tf

flux helm chart supports Prometheus metrics https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L301-L309  and offers a grafana dashboard https://github.com/fluxcd/flux/blob/master/chart/flux/values.yaml#L342-L349
We are looking to increase system visibility via Prometheus metrics and grafana dashboard, enabling this feature will provide us some basic visibility we need.
This is an additional feature and will not break existing setup.

add prometheus monitoring setting to flux chart

---

odc_k8s/config/flux.yaml

Tested in dea-dev
the helm value should be `dashboards`, this pr is to correct the typo.
No.

fix typo change dashboard to dashboards

---

cognito/README.md
cognito/cognito_auth.tf
cognito/variables.tf

Updated cognito module:
- Allow support for `email address` for username attribute during signup. You can do this by passing -
```
username_attributes = ["email"]
```
- Added parameter to enable username attribute case sensitivity. For example, user@example.com is now treated the same as User@example.com
```
enable_username_case_sensitivity = false
```
- revised schema attribute configuration block. For example, to add additional schema attributes
```
schema_additional_attributes = [
{
attribute_name           = "gender" …
```

cognito userpool configuration enhancements

---

examples/backend_init/terraform-backend.tf
odc_eks/cloudfront_distribution.tf
odc_eks/main.tf
odc_eks/outputs.tf
odc_eks/waf.tf

The recent release of `terraform-aws-provider` `v4.0.0` has remove support for some of the `aws_s3_bucket` resource configurations. This PR update/fix those changes. Refer release [v4.0.0](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.0.0) for more detail.
Reapply bucket configurations.

Terraform aws provider v4.0.0 updates

---

odc_eks/modules/eks/main.tf
odc_eks/modules/eks/workers.tf

I want to track costs of infra-dev in Cloudability by tag, and I can see most resources using the `stack_name` tag - except the EC2 worker nodes. Only `var.node_extra_tags` currently get passed, not `var.tags` - like every other resource.
It shouldn't make any difference other than adding additional generic tags. Unless there was some reason to only include `var.node_extra_tags`, which would otherwise break something if generic `var.tags` were …

Include var.tags in node workers

---

odc_k8s/README.md

Refer - #287
No changes to the module as Flux resources creation are already optional. Just updated the README with Flux V1 deprecated warning

update reademe - added deprecated warning for flux v1 installations

---

odc_k8s/fluxcloud.tf

During repeated setup/teardown tests on our infra cluster, I frequently had flux failing to create due to its' namespace not yet existing. This simply adds an explicit dependency to prevent that.
No functional changes.

Added explicit dependency to avoid an intermittent race condition

---

odc_eks/modules/eks/variables.tf
odc_eks/modules/eks/worker_policy.tf

The new AWS ECR pull though cache feature is a easy, fully AWS managed service that allows docker images to be cached within ECR from a number of other upstream image registries, such as dockerhub, ghcr etc.  It significantly reduces the number of pull requests sent to upstream registries, mitigating the issue of hitting pull rate limits.
As this is a new AWS feature, and not currently in-scope of the current deployment, risks or negative impacts of this change are negligible

Cluster node iam update

---

odc_eks/modules/eks/worker_image.tf

This flag was deprecated in < Kubernetes 1.23 and has been removed in 1.27 and now causes the `kubelet` to fail to start.
None, EKS 1.23 has no Extended Support so clusters should no longer exist.
I also adjusted the indentation of the args to `boostrap.sh` to be slightly more readable as they were misleading.

Remove --cloud-provider kubelet arg

---

odc_eks/modules/eks/main.tf

EKS supports access configuration via two methods: 
* `aws-auth` configmap
* `aws_eks_access_entry` resources
This change enables progressive migration of downstream configuration from the old style to the new style.
The use of configmap is headed out of favour:
* It's inherently a bit messy (a yaml blob stored as a string inside a kubernetes resource, that gets constructed using templating by terraform).
* It is prone to error and lacks a validation mechanism. 
* Typos fixed in the config map may not take effect for 30min or more, making debugging painful.
* Errors in the configmap may brick the cluster (revoking permission for actors to revert the change, since the config itself is an in-cluster resource).
* It tends to split the config across multiple terraform stages (cloud resources …

Enable EKS API access config

---

CHANGELOG.md
odc_eks/main.tf
odc_eks/waf.tf

> We made this change a while ago to our cluster in GNSS Informatics team so that we could move to AWS provider version 5.

Updates for AWS provider v5

---

odc_eks/modules/eks/worker_policy.tf

Fixing this error:
│ Error: Missing resource instance key
│
│   on ../../../../datacube-k8s-eks/odc_eks/modules/eks/worker_policy.tf line 85, in resource "aws_iam_role_policy_attachment" "eks_node_pullthrough":
│   85:   policy_arn = aws_iam_policy.ecr_pullthrough_cache.arn
│
│ Because aws_iam_policy.ecr_pullthrough_cache has "count" set, its attributes must be accessed on specific instances.
None

Fix a simple terraform error

---

odc_eks/main.tf
odc_eks/modules/eks/main.tf

A previous change adding an `access_config` block resulted in **new** clusters failing to allow auth for the rest of the toolchain (with no change for existing clusters). This rectifies that issue and there are also some minor `terraform fmt` fixes.

Restore previous cluster-auth behaviour

---

odc_eks/modules/eks/main.tf

When the access_config block was added recently it defaulted bootstrap_cluster_creator_admin_permissions to false but didn't affect the internal cluster setting since AWS considers it to only matter on creation. It's now causing Terraform to try to recreate existing clusters which is unlikely to ever be what the user wants.
None

Fix for admin_permissions trying to recreate clusters

---

odc_eks/modules/eks/variables.tf
odc_eks/modules/eks/worker_image.tf
odc_eks/vpc_support.tf

> To remove Tenable Nessus agent from our EKS nodes. Required by Service Request 108 https://planner.cloud.microsoft/webui/v1/plan/hvJYH6QZmEe5JPmgyCFyecgAGsrC/view/board/task/rz_hdFatEku59BuiRxQXCMgAK5XE?tid=645b613a-a64c-4250-975f-5f69787d028d
> To action this request, we need to make changes to the launch templates provisioned by the EKS stack in the following bitbucket repo: "https://bitbucket.org/geoscienceaustralia/datakube/src". This change allows the variable "update_default_version" to be set at the workspace level in bitbucket. This allows us to remove the nessus agent installation script from the launch template …

added update_default_version parameter and set default to false
