opendatacube/datacube-k8s-eks

addons/main.tf
Treat all terraform backends the same.
=> default to encrypted s3 remote state for addons

addons/alb_ingress.tf, addons/cloudwatch_logs.tf, addons/cluster_autoscaler.tf, addons/external_dns.tf, addons/flux.tf, addons/main.tf, addons/metrics_server.tf
+ whitespace fixes from running terraform format.
=> Pin helm charts to repo, so they don't re-install every run

addons/cloudwatch_logs.tf
Patches 14 vulnerabilities in the image
=> Bump the version of fluentd-cloudwatch from v1.3 to v1.4

addons/config/flux.yaml, addons/flux.tf, addons/repositories.tf
Remove weaveworks 
https://github.com/weaveworks/flux/wiki/MoveToFluxCD
=> Decommission weaveworks

docs/service_account.md, eks-policy.json, readme.md
First cut at #4 still needs to be reduced further in future
=> Add doco and policy json for generating service account

addons/jhub_cognito_auth.tf
New juhub cognito auth terraform code.  It creates a new user pool with email and name parameters, a client and callback domain.
tfvars need these two parameters:
jhub_cognito_auth_enabled = true
jhub_callback_url = "https://dev.sandbox.test.frontiersi.io/hub/oauth_callback"
=> Adding jhub cognito auth addon file

infra/main.tf, infra/modules/setup/main.tf, infra/modules/setup/variables.tf
=> Setup k8s provider using EKS resource attributes

nodes/main.tf, nodes/modules/workers/variables.tf, nodes/modules/workers/workers.tf, nodes/variables.tf
Enables the ability to increase size of spot asgs independently from regular nodes.
=> Spot nodes sizes

apply.sh, nodes/main.tf, nodes/modules/workers/variables.tf, nodes/modules/workers/worker_image.tf, nodes/variables.tf
This will allow normal or spot nodes to change their default storage size to be more applicable to their workload.
=> enable chaning storage sizes, and different storage for spot and normal nodes

addons/jhub_cognito_auth.tf
- This will create user groups for jhub cognito user pool
- No
=> Cognito user group

addons/waf.tf
=> added waf terraform addons

addons/waf.tf
test webacl modules for WAF configuration
No
=> test with older version of webacl-supporting-resources module

addons/waf.tf
test webacl modules for WAF configuration
No
=> commented out webacl-supporting-resources module as it is erroring out.

addons/_variables.tf, addons/waf.tf
=> verbalised environment var

addons/_variables.tf, addons/waf.tf
WAF - added resources to enable waf logging
No
=> added resources required to enable logging

addons/waf.tf
=> WAF addons: fixed typo

addons/waf.tf
WAF addons: fix typo and code cleanup
No
=> WAF addons: fix typo and code cleanup

addons/waf.tf
WAF addons: enable waf logging configuration
No
=> WAF addons: enable waf logging configuration

addons/waf.tf
WAF addons: enable cloudwatch logging for firehose delivery stream error logs
No
=> WAF addons: enable cloudwatch logging for firehose delivery stream error logs

addons/_variables.tf, addons/waf.tf
WAF addons: make all waf resources optional and code refactor
No
=> make all waf resources optional

addons/waf.tf
waf addons: fix resource referencing
No
=> need count.index for referring resource

addons/waf.tf
WAF addons: fix missing count.index for ref resource
No
=> fix missing count.index for ref resource

addons/waf.tf
WAF addons: fix resource ref
No
=> fix resource ref

nodes/modules/workers/worker_image.tf
- added a label to on demand instance so that can configure affinity for container deployments
- all the on demand nodes require recreate for the change to take affect
=> add label to on demand instance

Makefile, docs/patching_upgrading.md, scripts/roll_instances.sh
- added a script to support rolling patch deploy that ensure applications are healthy during patching
- No impact. New Feature - rolling update
=> add a script to do rolling update - patch deploy

examples/stage/odc_eks/odc_eks.tf, examples/stage/odc_eks/outputs.tf, examples/stage/odc_k8s/odc_k8s.tf, examples/stage/odc_k8s/provider.tf, odc_eks/main.tf, odc_eks/modules/eks/user_policy.tf, odc_eks/modules/eks/variables.tf, odc_eks/outputs.tf, odc_eks/variables.tf, odc_k8s/aws_auth.tf, odc_k8s/provider.tf, odc_k8s/variables.tf
- rework aws_auth tempalte as per #141 
- rework aws_auth tempalte as per #141
=> rework aws_auth by passing users and roles variables

odc_k8s/install_extra_software.tf
added a fix as it was complaining about file or directory not present
=> fix the install script

docs/variables.md
- updated docs foe WAF
- no impact. docs update
=> update docs for WAF variables

infra/modules/database_layer/db.tf
we had a variable that was supposed to make the RDS multi-az, 
this variable now makes the RDS mulit-az
None
=> RDS now honours multi-az var

examples/stage/odc_k8s/odc_k8s.tf, odc_k8s/aws_auth.tf, odc_k8s/variables.tf
aws_auth template update to support list of node role ARNs and user role ARNs. 
aws_auth enhancement
=> update aws_auth configmap to support list of node role ARNs and user role ARNs

examples/stage/odc_eks/outputs.tf, examples/stage/odc_k8s/odc_k8s.tf
Delete left behind var as part of #162 
Fix broken CI
=> remove left behind/unused vars

addons/config/efs-provisioner.tpl, addons/efs.tf, docs/variables.md, odc_eks/modules/database_layer/db.tf, odc_eks/waf.tf
- bringing latest changes from `master` branch to `terraform-aws-odc` branch
- Synchronise with master branch
=> Sync with master

examples/stage/odc_eks/odc_eks.tf, examples/stage/odc_eks/outputs.tf, examples/stage/odc_k8s_sandbox/config/jhub.yaml, examples/stage/odc_k8s_sandbox/db_creds.tf, examples/stage/odc_k8s_sandbox/jhub.tf, examples/stage/odc_k8s_sandbox/main.tf, examples/stage/odc_k8s_sandbox/namespaces.tf, examples/stage/odc_k8s_sandbox/odc_k8s_data_providers.tf, examples/stage/odc_k8s_sandbox/provider.tf, examples/stage/odc_k8s_sandbox/worker_image.tf, examples/stage/odc_k8s_sandbox/workers.tf, odc_eks/modules/cognito/cognito_auth.tf, odc_eks/modules/cognito/output.tf, odc_eks/outputs.tf
- This PR shows an example for how to setup jupyterhub notebook environment. It is a continuity of PR #173. Associate jhub hr provisioner PR (https://github.com/opendatacube/flux-odc-sample/pull/6) raised for end-to-end testing
=> Jhub setup

examples/stage/odc_eks/odc_eks.tf, odc_eks/main.tf
- add SubnetType tag to differentiate subnets. This is useful for filtering subnets. little refactoring.
- cluster version upgrade - 1.14
=> Tag subnets

addons/repositories.tf
- delete coreos repo from helm repo list. This repo is no longer available publicly - we getting Error 403 Forbidden.
- Fix broken pipeline. Delete coreos repo from helm repo list. This repo is no longer available publicly - we getting Error 403 Forbidden.
=> delete coreos repo from helm repo list

examples/stage/odc_apps_k8s/odc_k8s_data_providers.tf, examples/stage/odc_eks/outputs.tf, examples/stage/odc_k8s/odc_k8s_data_providers.tf, examples/stage/odc_k8s_sandbox/odc_k8s_data_providers.tf, odc_eks/main.tf, odc_eks/outputs.tf
- fix certificate_arn index invalid issue and code cleanup.  this will help in clean destroy.
=> fix certificate_arn index invalid issue and code cleanup

odc_k8s/config/flux.yaml, odc_k8s/flux.tf
- use tf template_file to set flux config - replace set value settings.
- update flux config to connect to fluxcloud as optional settings. 
- No impact.
=> update flux config to connect to fluxcloud - optional settings

odc_eks/modules/eks/master_sg.tf, odc_eks/modules/eks/worker_sg.tf
- revised eks cluster and node security group
- No impact. Cluster should work as before. It does in place update.
=> Slight adjustment to eks cluster and node security group

odc_eks/cloudfront_distribution.tf
- This change will allow us to create a cf certificate with list of domains defined in cf_custom_aliases
- No impact. The changes are made that doesn't break cloudfront.
=> cf certificate create: create certificate with multiple domains listed in cf_custom_aliases

odc_eks/cloudfront_distribution.tf
- added a lifecycle for cf cert resource. this will allow us to update cf before deleting a cert in use.
- Fix for cf cert update.
=> added lifecycle for cf cert

odc_k8s/aws_auth.tf
=> fix typo - variable declaration

examples/scripts/init_ows_db.sh, examples/scripts/init_sandbox_db.sh, examples/stage/01_odc_eks/db.tf, examples/stage/01_odc_eks/odc_eks.tf, examples/stage/01_odc_eks/outputs.tf, examples/stage/02_odc_k8s/provider.tf, examples/stage/03_odc_apps_k8s/data_providers.tf, examples/stage/03_odc_apps_k8s/db_creds.tf, examples/stage/03_odc_apps_k8s/odc_roles_web.tf, examples/stage/03_odc_apps_k8s/ows.tf, examples/stage/04_odc_k8s_sandbox/config/jupyterhub.yaml, examples/stage/04_odc_k8s_sandbox/data_providers.tf, examples/stage/04_odc_k8s_sandbox/db_creds.tf, examples/stage/04_odc_k8s_sandbox/jupyterhub.tf
=> example - update example

odc_eks/modules/eks/worker_policy.tf
- fix AWS SSM role.
- should unblock deployment due to previous issue got merged
=> sorry for typo. fix ssm policy

cognito/README.md, cognito/cognito_auth.tf, cognito/pinpoint.tf, cognito/variables.tf
#251 Enables PinPoint for all app-clients to capture user behavbiour
Extra resource usage / costs due to the pinpoint service. To avoid surprises, this is disabled by default.
=> #251 Enable conditional pinpoint for app_clients

cognito/README.md, cognito/cognito_auth.tf, cognito/output.tf, cognito/pinpoint.tf, cognito/variables.tf
#251 to get valuable user analytics from Cognito based logins.
Disabled by default. Applied to all application clients. Will lead to extra costs
=> Feat enable pp

odc_eks/main.tf
solve #255 odc-eks module - fix inconsistent cluster ids
No impact to existing setup
=> issue-255: odc-eks module - fix inconsistent cluster ids

odc_eks/README.md, odc_eks/main.tf, odc_eks/modules/eks/variables.tf, odc_eks/modules/eks/worker_image.tf, odc_eks/variables.tf
=> Support extra kubelet args

odc_eks/main.tf
=> Bump vpc module version

odc_eks/README.md, odc_eks/outputs.tf
This change will enable us to route traffic from our cluster to another VPC over a peering connection.
=> Output public route table ids

odc_eks/modules/eks/workers.tf
=> fix spot nodegroup tag - nodetype tag attribute
